<?xml version="1.0" encoding="UTF-8"?>
<!-- <?xml-stylesheet href="file.css" type="text/css"?> -->
<!DOCTYPE BOOKINFO [
    <!ELEMENT BOOKINFO (book+)>
    <!ELEMENT book (title,author,ISBN,edition,price)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT ISBN (#PCDATA)>
    <!ELEMENT edition (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
]>

<BOOKINFO>
    <book>
        <title>Let Us Sex</title>
        <author>Abhishek Gururani</author>
        <ISBN>1883393</ISBN>
        <edition>69th</edition>
        <price>420R</price>
    </book>

    <book>
        <title>Let us cunni</title>
        <author>Abhishek Gururani</author>
        <ISBN>28382828</ISBN>
        <edition>1st</edition>
        <price>420R</price>
    </book>

</BOOKINFO>